[#configuring-hosting-service-cluster-configure-non-bm]
= Configuring hosted control plane clusters on non bare metal platforms (Tech Preview)

You can deploy hosted control planes by configuring a cluster to function as a hosting cluster. The hosting cluster is the {ocp-short} cluster where the control planes are hosted. The hosting cluster is also known as the _management_ cluster.

*Note:* The management cluster is not the same thing as the _managed_ cluster. A managed cluster is a cluster that the hub cluster manages.

The hosted control planes feature is enabled by default.

The {mce-short} 2.4 supports only the default `local-cluster`, which is a hub cluster that is managed, and the hub cluster as the hosting cluster. On {product-title-short} 2.9, you can use the managed hub cluster, also known as the `local-cluster`, as the hosting cluster.

A _hosted cluster_ is an {ocp-short} cluster with its API endpoint and control plane that are hosted on the hosting cluster. The hosted cluster includes the control plane and its corresponding data plane. You can use the {mce-short} console or the hosted control plane command line interface, `hcp`, to create a hosted cluster. The hosted cluster is automatically imported as a managed cluster. If you want to disable this automatic import feature, see _Disabling the automatic import of hosted clusters into {mce-short}_.

*Important:*

- Each hosted cluster must have a unique name in order for {mce-short} to manage it.

- Run the hub cluster and workers on the same platform for hosted control planes.

- Each hosted cluster must have a unique name in order for {mce-short} to manage it.

- A hosted cluster cannot be created in the namespace of a {mce-short} managed cluster.

- To provision hosted control planes on non bare metal platforms, you can use the Agent platform. The Agent platform uses the central infrastructure management service to add worker nodes to a hosted cluster. For an introduction to the central infrastructure management service, see xref:../cluster_lifecycle/cim_enable.adoc#enable-cim[Enabling the central infrastructure management service].

- Each non bare metal host must be started with a Discovery Image that the central infrastructure management provides. You can start the hosts manually or through automation by using `Cluster-Baremetal-Operator`. After each host starts, it runs an Agent process to discover the host details and complete the installation. An `Agent` custom resource represents each host.

- When you create a hosted cluster with the Agent platform, HyperShift installs the Agent Cluster API provider in the hosted control plane namespace.

- When you scale up a node pool, a machine is created. The Cluster API provider finds an Agent that is approved, is passing validations, is not currently in use, and meets the requirements that are specified in the node pool specification. You can monitor the installation of an Agent by checking its status and conditions.

- When you scale down a node pool, Agents are unbound from the corresponding cluster. Before you can reuse the clusters, you must restart them by using the Discovery image to update the number of nodes.

- When you configure storage for hosted control planes, consider the recommended etcd practices. To ensure that you meet the latency requirements, dedicate a fast storage device to all hosted control plane etcd instances that run on each control-plane node. You can use LVM storage to configure a local storage class for hosted etcd pods. For more information, see _Recommended etcd practices_ and _Persistent storage using logical volume manager storage_ in the {ocp-short} documentation.

[#hosting-service-cluster-configure-limitation-non-bm]
== Limitations

You can review the following limitations before provisioning hosted control planes:

* You can boot your non bare metal hosts with the ISO only.

* You must provision hosted control planes manually on non bare metal hosts.

[#hosting-service-cluster-configure-prereq-non-bm]
== Prerequisites

You must have the following prerequisites to configure a hosting cluster:

* You need the {mce} 2.2 and later installed on an {ocp-short} cluster. The {mce-short} is automatically installed when you install {product-title-short}. You can also install {mce-short} without {product-title-short} as an Operator from the {ocp-short} OperatorHub.

* The {mce-short} must have at least one managed {ocp-short} cluster. The `local-cluster` is automatically imported in {mce-short} 2.2 and later. See xref:../install_upgrade/adv_config_install.adoc#advanced-config-engine[Advanced configuration] for more information about the `local-cluster`. You can check the status of your hub cluster by running the following command:
+
----
oc get managedclusters local-cluster
----

* You need to enable central infrastructure management. For more information, see xref:../cluster_lifecycle/cim_enable.adoc#enable-cim[Enabling the central infrastructure management service].

* You need to xref:../hosted_control_planes/install_hcp_cli.adoc#hosted-install-cli[install the hosted control plane command line interface].

[#firewall-port-reqs-non-bare-metal]
== Firewall and port requirements for non bare metal platforms

[#infrastructure-reqs-nonbare-metal]
== Infrastructure requirements for non bare metal platforms
